
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Enjoy Life Blog
description: Enjoy life and record growth
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
#show_downloads: true